#!/bin/bash
# Get past versions of a file in a git repository
# get_all_versions filename
# Adapted from stackoverflow.com/users/26510/brad-parks

index=1

file=$1
for commit in $(git log --pretty=format:"%h" "$1")
do
  out="$1.$(printf %03d "$index").$commit.${file##*.}"
  git show "$commit:./$1" > "$out"
  let index++
done
